### ISSUE TITLE
deleted coab service instance leaks in secrets and template git repos

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation-broker#221]
### Expected behavior

As a paas-templates operator, in order to avoid human errors within service instances directories in git repos, I expected deleted service instances to be removed automatically

### Observed behavior

COA is preventing COAB from properly cleaning up deleted service instances in templates and secrets repos, see  https://github.com/orange-cloudfoundry/cf-ops-automation/issues/67

**Comment by JCL38-ORANGE** [comment]
will be embedded in next coab release (v0.30)
