### ISSUE TITLE
Full COA conventions support

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/cf-ops-automation-broker#31]
As a service template author, I will follow the conventions expected by COA (https://github.com/orange-cloudfoundry/cf-ops-automation#ops-files).

COA Broker must be fully compliant with these conventions : 

- [x] Bosh deployment resources template format

- [x] Bosh cli v2 specific features support (vars-files and ops-files)

- [x] Improve embeded  file management (deployment-dependencies) 

- [x] Iaas specifics support

**Comment by gberche-orange** [comment]
@JCL38-ORANGE rather than having COAB check and enforce COA bosh deployment format, I would suggest to try to blindly symlink the deployment model files, and rely on the service authors to properly craft them.

This would restrict COAB maintenance as COA resource format gets enriched and evolves.

**Comment by JCL38-ORANGE** [comment]
Full COA conventions support is available in mysql branch.
