### ISSUE TITLE
Force trigger COA build (template-refresh) on user-triggered service instance no-op update

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/cf-ops-automation-broker#33]
As a service author, I need COAB to force a COA build of the service instance deployment for every service instance update, in order to provide ways for a service instance to get updates I make to service models.

This is a workaround for https://github.com/orange-cloudfoundry/cf-ops-automation/issues/144 

* When: any service instance update is requested
* Then: COAB commits into paas-template a marker file (e.g. `last-update-date.txt`) with the intent of forcing the detection of input changes on the `paas-template-<service-instance_id>`  resource, which in turn pick up the changes made to the symlinked deployment model, and will update the service instance with them. This file has no other impacts than triggering the new build (i.e. it is ignored by the tasks of the `deploy` concourse job )

Service operators that wish to upgrade all service instances would have to loop other all service instances using the CF CLI/API or perform the same git commit on paas-templates (e.g. a git rebase of the service-instances branch against the paas-template current version commit id)

**Comment by gberche-orange** [comment]
For the use-case of service operators that wish to upgrade all service instances, the current service instance rebase operations that are performed on paas-templates deployments, see https://github.com/orange-cloudfoundry/paas-templates/issues/304 `Rebasing tasks + reset-merged-wip-features job` are likely to already trigger new concourse deployments

**Comment by poblin-orange** [comment]
see #40

**Comment by gberche-orange** [comment]
Closing for now as service instance rebases triggered by service operators trigger COA build (stemcell + release updates) and #245 handle operator triggered updates or #40 handle user-triggered updates
